version: '3.14'

services:
  nginx:
    image: nginx:latest
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - ewidencja_network
    depends_on:
      - backend

  backend:
    build:
      context: ./SchoolProject/SchoolProject.Api
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./SchoolProject/:/SchoolProject/
    networks:
      - ewidencja_network
  
  postgres:
    container_name: postgres
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5434
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin!
      - POSTGRES_DB=evidention
    networks:
      - ewidencja_network

  scripts:
    container_name: cron-scripts
    build:
      context: ./scripts
      dockerfile: ./Dockerfile
    networks:
      - ewidencja_network

volumes:
  postgres_data:

networks:
  ewidencja_network:
    driver: bridge